[package]
name = "qrcc-wasm"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["render"]
render = []
decode = ["dep:qrcc-scan"]

[dependencies]
qrcc-kernel.workspace = true
qrcc-generate.workspace = true
qrcc-scan = { workspace = true, optional = true }
serde.workspace = true
serde_json.workspace = true
wasm-bindgen.workspace = true
console_error_panic_hook.workspace = true

[lints]
workspace = true
